# Basic Site Info
title: Hverlandisk Útvarpsnet
description: "Hverland's national public broadcasting corporation"
author: Hverlandisk Útvarpsnet

# Site Flag
flag:
  show: true
  path: /assets/flag.svg

# Comments
disqus:
  enabled: false
  shortname: HUN  #REPLACEME

# Analytics
google_analytics: G-GRV8PX7ZN1

# Ads
adsense:
  enabled: true
  data-ad-client: ca-pub-9280169319319657  #REPLACEME

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/
  staff:
    output: true
    permalink: /about/staff/:title

# Build settings
repository: petermgrund/HUN
markdown: kramdown
remote_theme: morpheus636/jekyll-news
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
